# k8s/deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-py
  labels:
    app: hello-py
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-py
  template:
    metadata:
      labels:
        app: hello-py
    spec:
      containers:
        - name: hello-py
          image: krystofl/hello-py:v1.1
          volumeMounts:
          - name: secret-volume
            mountPath: "/"
            readOnly: true
      volumes:
      - name: secret-volume
        secret:
          secretName: my-secret
          items:
          - key: secret.txt
            path: my-mounted-secret.txt
