apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello-py-cronjob
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello-py-cronjob
            image: krystofl/hello-py:latest
            args:
            - ./hello.py
            - -n
            - Bob
            volumeMounts:
            - name: secret-volume
              mountPath: "/secrets"
              readOnly: true
          restartPolicy: OnFailure
          volumes:
          - name: secret-volume
            secret:
              secretName: my-secret
              items:
              - key: secret.txt
                path: my-mounted-secret.txt
